# =========================
# Basic Site Settings
# =========================
locale        : "en-US"
site_theme    : "default"   # custom var used by AcademicPages (default / air)

# Use AcademicPages as a remote theme (correct repo name)
remote_theme  : academicpages/academicpages.github.io

title         : "Zhiyu Shi / Graduate student, Princeton University"
title_separator: "-"
name          : &name "Zhiyu Shi"
description   : &description "Multiscale modeling of plasma-assisted combustion and catalysis"

# Your GitHub Pages root URL and repo (make sure these match your actual repo/user)
url           : "https://zhi-yu-shi.github.io"
baseurl       : ""                         # keep empty for user site
repository    : "Zhi-yu-Shi/zhi-yu-shi.github.io"

# =========================
# Author (left sidebar)
# =========================
author:
  avatar     : "profile.png"
  name       : "Zhiyu Shi"
  pronouns   : "he/him"
  bio        : "PhD at Princeton | Plasma-assisted combustion & catalysis"
  location   : "Princeton, NJ"
  employer   : "Princeton University"
  uri        :
  email      : "zs3643@princeton.edu"

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?user=USgOMmMAAAAJ&hl=en"
  orcid        : "https://orcid.org/0009-0008-8786-1298"
  researchgate : "https://www.researchgate.net/scientific-contributions/Zhiyu-Shi-2241567204"

  # Code / repos
  github     : "Zhi-yu-Shi"

  # Social (leave blank if not used)
  bluesky    :
  linkedin   :
  twitter    :
  zhihu      :

# =========================
# Publication categories (keys used by each post's `category`)
# =========================
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# =========================
# Site Settings
# =========================
teaser        :
breadcrumbs   : false
words_per_minute: 160
future        : true
read_more     : "disabled"
talkmap_link  : false

comments:
  provider    :
  disqus:
    shortname :
  discourse:
    server    :
  facebook:
    appid     :
    num_posts :
    colorscheme:

staticman:
  allowedFields : ['name', 'email', 'url', 'message']
  branch        : "gh-pages"
  commitMessage : "New comment."
  filename      : comment-{@timestamp}
  format        : "yml"
  moderation    : true
  path          : "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email      : "md5"
  generatedFields:
    date:
      type     : "date"
      options:
        format : "iso8601"

atom_feed:
  hide         : false
  path         :

# =========================
# SEO / Social
# =========================
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username     :
facebook:
  username     :
  app_id       :
  publisher    :
og_image       :
og_description :

social:
  type         :
  name         :
  links        :

# =========================
# Analytics
# =========================
analytics:
  provider     : "false"
  google:
    tracking_id:

# =========================
# Files to include/exclude
# =========================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# =========================
# Conversion / Markdown
# =========================
markdown           : kramdown
highlighter        : rouge
lsi                : false
excerpt_separator  : "\n\n"
incremental        : false

kramdown:
  input            : GFM
  hard_wrap        : false
  auto_ids         : true
  footnote_nr      : 1
  entity_output    : as_char
  toc_levels       : 1..6
  smart_quotes     : lsquo,rsquo,ldquo,rdquo
  enable_coderay   : false

# =========================
# Collections
# =========================
collections:
#  teaching:
#    output    : true
#    permalink : /:collection/:path/
  publications:
    output    : true
    permalink : /:collection/:path/
#  portfolio:
#    output    : true
#    permalink : /:collection/:path/
  talks:
    output    : true
    permalink : /:collection/:path/

# =========================
# Defaults for each collection
# =========================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout         : single
      author_profile : true
      read_time      : true
      comments       : true
      share          : true
      related        : true

  - scope:
      path: ""
      type: pages
    values:
      layout         : single
      author_profile : true

  - scope:
      path: ""
      type: teaching
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true

  - scope:
      path: ""
      type: publications
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true

  - scope:
      path: ""
      type: portfolio
    values:
      layout         : single
      author_profile : true
      share          : true
      comment        : true

  - scope:
      path: ""
      type: talks
    values:
      layout         : talk
      author_profile : true
      share          : true

# =========================
# Sass/SCSS
# =========================
sass:
  sass_dir : _sass
  style    : compressed

# =========================
# Output / Permalinks
# =========================
permalink    : /:categories/:title/
timezone     : Etc/UTC
# paginate   : 5
# paginate_path: /page:num/

# =========================
# Plugins (GitHub Pages-safe)
# =========================
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# For --safe mode mimic (optional)
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =========================
# Archives
# =========================
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# =========================
# HTML Compression
# =========================
compress_html:
  clippings: all
  ignore:
    envs: development
